### ISSUE TITLE
Core tests shouldn't depend on app-specific configuration

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/server_core#14]
Some of the tests are failing when run in a content server environment without policies in the config file. They should be runnable from any of the environments.

```
======================================================================
ERROR: content.core.tests.test_opds.TestOPDS.test_empty_groups_feed_is_none
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/amyslagle/dev/content/env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/amyslagle/dev/content/core/tests/test_opds.py", line 765, in test_empty_groups_feed_is_none
    config['policies'][Configuration.FEATURED_LANE_SIZE] = 10
KeyError: 'policies'
```

**Comment by leonardr** [comment]
Pretty sure I fixed this.
